server:
  port: ${PORT:8081}

app-config:
  secrets:
    api-secret: ${API_SECRET:U2VjcmV0U29RdWVFbUJhc2U2NEtLS0sK}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: product-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:product-db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123456}
    tomcat:
      max-active: 3

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      testWhileIdle: true
      validationQuery: SELECT 1
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
        temp:
          use_jdbc_metadata_default: false

  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql